server:
  port: ${APP_SUBSCRIPTION_SERVICE_PORT:0}

spring:
  application:
    name: ${APP_SUBSCRIPTION_SERVICE_NAME:app-subscription-service}
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: ${APP_SUBSCRIPTION_SERVICE_MONGODB_URI:uri}
      database: ${APP_SUBSCRIPTION_SERVICE_MONGODB_DATABASE:app-subscription-db}
      auto-index-creation: true

eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
    enabled-by-default: ${APP_SUBSCRIPTION_SERVICE_ACTUATOR_ENABLED:true}

  prometheus:
    metrics:
      export:
        enabled: true

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

springdoc:
  swagger-ui:
    path: /api/documentation