###
GET http://localhost:8080/v1/subscriptions

###
POST http://localhost:8080/v1/subscriptions
Content-Type: application/json

{
  "chatId": -12,
  "templateId": "00099jasdasd",
  "type": "RSS",
  "context": {
    "url": "www.xxx.www"
  },
  "filter": {}
}

###
PATCH http://localhost:8080/v1/subscriptions/65f358a6f57a2b122253118f